name: Manual-Parallel

on:
  workflow_dispatch:
    inputs:
      trigger_next:
        description: 'Whether to run the subsequent workflows after triggering this one manully.'
        required: false
        default: false
  repository_dispatch:
    types: [manual-parallel]

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Manual-parallel-1-release"
